"""
Risk Analyst Agent
==================

An autonomous AI agent specialized in comprehensive risk assessment and management.
This agent solves the critical real-world pain point of delayed risk detection and inadequate
risk monitoring in financial portfolios, which can lead to significant losses.

Key Features:
- Real-time Value at Risk (VaR) calculation using multiple methodologies
- Stress testing and scenario analysis
- Correlation analysis and regime detection
- Automated risk limit monitoring and alerting
- Credit risk assessment and counterparty exposure
- Liquidity risk analysis
- Market risk decomposition
"""

import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from typing import Dict, List, Any
from dataclasses import dataclass
import logging
from scipy import stats
import warnings
import yfinance as yf
from .base_agent import BaseAgent, AgentTask, AgentPriority

warnings.filterwarnings('ignore')


@dataclass
class RiskMetrics:
    """Container for comprehensive risk metrics"""
    var_95: float
    var_99: float
    expected_shortfall_95: float
    expected_shortfall_99: float
    maximum_drawdown: float
    volatility: float
    beta: float
    tracking_error: float
    information_ratio: float
    downside_deviation: float
    calmar_ratio: float


@dataclass
class StressTestResult:
    """Result of stress testing scenario"""
    scenario_name: str
    portfolio_impact: float
    individual_impacts: Dict[str, float]
    probability_estimate: float
    time_horizon: str
    confidence_level: float


@dataclass
class RiskAlert:
    """Risk alert generated by the system"""
    alert_type: str
    severity: AgentPriority
    message: str
    affected_assets: List[str]
    current_value: float
    threshold_value: float
    recommendation: str
    timestamp: datetime


class RiskAnalystAgent(BaseAgent):
    """AI agent responsible for comprehensive risk analysis and monitoring"""
    
    def __init__(self):
        super().__init__(
            agent_id="risk_analyst",
            name="Risk Analyst Agent",
            capabilities=[
                "var_calculation",
                "stress_testing",
                "correlation_analysis",
                "liquidity_analysis",
                "credit_assessment",
                "risk_monitoring",
                "scenario_analysis",
                "risk_decomposition"
            ]
        )
        
        # Risk thresholds and limits
        self.risk_limits = {
            'portfolio_var_95': 0.02,  # 2% daily VaR limit
            'portfolio_var_99': 0.035,  # 3.5% daily VaR limit
            'max_individual_weight': 0.25,  # 25% max single asset
            'max_sector_weight': 0.40,  # 40% max sector concentration
            'min_liquidity_ratio': 0.05,  # 5% minimum liquid assets
            'max_correlation': 0.80,  # 80% max correlation between assets
            'max_beta': 1.50,  # 1.5 maximum portfolio beta
            'max_drawdown': 0.15  # 15% maximum drawdown
        }
        
        # Risk models and methodologies
        self.var_methods = {
            'historical_simulation': self._historical_simulation_var,
            'parametric_var': self._parametric_var,
            'monte_carlo_var': self._monte_carlo_var,
            'cornish_fisher_var': self._cornish_fisher_var
        }
        
        # Stress test scenarios
        self.stress_scenarios = {
            'market_crash_2008': {'equity_shock': -0.40, 'bond_shock': 0.05, 'volatility_shock': 2.0},
            'covid_crash_2020': {'equity_shock': -0.35, 'bond_shock': -0.02, 'volatility_shock': 3.0},
            'interest_rate_shock': {'equity_shock': -0.15, 'bond_shock': -0.10, 'volatility_shock': 1.5},
            'inflation_shock': {'equity_shock': -0.20, 'bond_shock': -0.15, 'volatility_shock': 1.8},
            'geopolitical_crisis': {'equity_shock': -0.25, 'bond_shock': 0.03, 'volatility_shock': 2.2}
        }
        
        # Historical data cache
        self.price_data_cache = {}
        self.returns_cache = {}
        
        # Risk monitoring state
        self.active_alerts: List[RiskAlert] = []
        self.risk_metrics_history = []
        
        self.logger = logging.getLogger("agent.risk_analyst")
    
    async def process_task(self, task: AgentTask) -> Dict[str, Any]:
        """Process risk analysis tasks"""
        task_type = task.task_type
        parameters = task.parameters
        
        try:
            if task_type == "var_calculation":
                return await self._calculate_var(parameters)
            elif task_type == "stress_testing":
                return await self._perform_stress_test(parameters)
            elif task_type == "correlation_analysis":
                return await self._analyze_correlations(parameters)
            elif task_type == "liquidity_analysis":
                return await self._analyze_liquidity(parameters)
            elif task_type == "risk_monitoring":
                return await self._monitor_risk_limits(parameters)
            elif task_type == "scenario_analysis":
                return await self._scenario_analysis(parameters)
            elif task_type == "risk_decomposition":
                return await self._decompose_portfolio_risk(parameters)
            elif task_type == "credit_assessment":
                return await self._assess_credit_risk(parameters)
            else:
                raise ValueError(f"Unknown task type: {task_type}")
                
        except Exception as e:
            self.logger.error(f"Error processing task {task.task_id}: {e}")
            raise
    
    async def analyze_data(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze market and portfolio data for risk assessment"""
        try:
            portfolio_data = data.get('portfolio_data', {})
            market_data = data.get('market_data', {})
            
            # Comprehensive risk analysis
            analysis = {
                'risk_metrics': await self._calculate_comprehensive_risk_metrics(portfolio_data),
                'risk_alerts': await self._generate_risk_alerts(portfolio_data, market_data),
                'stress_test_summary': await self._quick_stress_test(portfolio_data),
                'correlation_warnings': await self._check_correlation_risks(market_data),
                'liquidity_assessment': await self._assess_liquidity_risk(portfolio_data),
                'var_breakdown': await self._calculate_var_breakdown(portfolio_data),
                'regime_analysis': await self._analyze_market_regime(market_data)
            }
            
            return analysis
            
        except Exception as e:
            self.logger.error(f"Error analyzing data: {e}")
            return {'error': str(e)}
    
    async def _calculate_var(self, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Calculate Value at Risk using multiple methodologies"""
        try:
            portfolio = parameters.get('portfolio', {})
            confidence_levels = parameters.get('confidence_levels', [0.95, 0.99])
            time_horizon = parameters.get('time_horizon', 1)  # days
            methods = parameters.get('methods', ['historical_simulation', 'parametric_var'])
            
            # Get portfolio returns data
            assets = list(portfolio.keys())
            weights = np.array(list(portfolio.values()))
            
            returns_data = await self._get_returns_data(assets)
            portfolio_returns = (returns_data * weights).sum(axis=1)
            
            var_results = {}
            
            for method in methods:
                if method in self.var_methods:
                    var_func = self.var_methods[method]
                    method_results = {}
                    
                    for confidence_level in confidence_levels:
                        var_value = await var_func(portfolio_returns, confidence_level, time_horizon)
                        method_results[f'var_{int(confidence_level*100)}'] = var_value
                        
                        # Calculate Expected Shortfall (Conditional VaR)
                        es_value = await self._calculate_expected_shortfall(
                            portfolio_returns, confidence_level, time_horizon
                        )
                        method_results[f'es_{int(confidence_level*100)}'] = es_value
                    
                    var_results[method] = method_results
            
            # Model averaging for robust VaR estimate
            averaged_var = await self._average_var_estimates(var_results, confidence_levels)
            
            # Risk decomposition
            individual_var = await self._calculate_individual_var(returns_data, weights, confidence_levels[0])
            
            return {
                'var_estimates': var_results,
                'averaged_var': averaged_var,
                'individual_var': individual_var,
                'portfolio_volatility': portfolio_returns.std() * np.sqrt(252),
                'calculation_timestamp': datetime.now().isoformat(),
                'time_horizon_days': time_horizon
            }
            
        except Exception as e:
            self.logger.error(f"VaR calculation failed: {e}")
            raise
    
    async def _perform_stress_test(self, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Perform comprehensive stress testing"""
        try:
            portfolio = parameters.get('portfolio', {})
            scenarios = parameters.get('scenarios', list(self.stress_scenarios.keys()))
            custom_scenarios = parameters.get('custom_scenarios', {})
            
            stress_results = []
            
            # Test predefined scenarios
            for scenario_name in scenarios:
                if scenario_name in self.stress_scenarios:
                    scenario = self.stress_scenarios[scenario_name]
                    result = await self._apply_stress_scenario(portfolio, scenario_name, scenario)
                    stress_results.append(result)
            
            # Test custom scenarios
            for scenario_name, scenario in custom_scenarios.items():
                result = await self._apply_stress_scenario(portfolio, scenario_name, scenario)
                stress_results.append(result)
            
            # Reverse stress testing - find scenarios that cause 10% loss
            reverse_stress_result = await self._reverse_stress_test(portfolio, target_loss=0.10)
            
            # Monte Carlo stress testing
            monte_carlo_results = await self._monte_carlo_stress_test(portfolio, n_simulations=10000)
            
            return {
                'stress_test_results': stress_results,
                'reverse_stress_test': reverse_stress_result,
                'monte_carlo_stress': monte_carlo_results,
                'worst_case_scenario': max(stress_results, key=lambda x: abs(x.portfolio_impact)),
                'stress_test_timestamp': datetime.now().isoformat()
            }
            
        except Exception as e:
            self.logger.error(f"Stress testing failed: {e}")
            raise
    
    async def _analyze_correlations(self, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze correlation structure and identify risks"""
        try:
            assets = parameters.get('assets', [])
            lookback_period = parameters.get('lookback_period', 252)  # 1 year
            
            returns_data = await self._get_returns_data(assets, period=lookback_period)
            correlation_matrix = returns_data.corr()
            
            # Identify high correlations
            high_correlations = []
            correlation_warnings = []
            
            for i in range(len(assets)):
                for j in range(i+1, len(assets)):
                    corr = correlation_matrix.iloc[i, j]
                    if abs(corr) > self.risk_limits['max_correlation']:
                        high_correlations.append({
                            'asset1': assets[i],
                            'asset2': assets[j],
                            'correlation': corr,
                            'risk_level': 'HIGH' if abs(corr) > 0.9 else 'MEDIUM'
                        })
                        
                        correlation_warnings.append(
                            f"High correlation ({corr:.3f}) between {assets[i]} and {assets[j]}"
                        )
            
            # Rolling correlation analysis
            rolling_correlations = await self._analyze_rolling_correlations(returns_data)
            
            # Principal Component Analysis for dimensionality
            pca_analysis = await self._perform_pca_analysis(returns_data)
            
            # Correlation regime detection
            regime_analysis = await self._detect_correlation_regimes(returns_data)
            
            return {
                'correlation_matrix': correlation_matrix.to_dict(),
                'high_correlations': high_correlations,
                'correlation_warnings': correlation_warnings,
                'rolling_correlations': rolling_correlations,
                'pca_analysis': pca_analysis,
                'regime_analysis': regime_analysis,
                'analysis_timestamp': datetime.now().isoformat()
            }
            
        except Exception as e:
            self.logger.error(f"Correlation analysis failed: {e}")
            raise
    
    async def _historical_simulation_var(self, returns: pd.Series, confidence_level: float, time_horizon: int) -> float:
        """Calculate VaR using historical simulation"""
        percentile = (1 - confidence_level) * 100
        var_value = np.percentile(returns, percentile) * np.sqrt(time_horizon)
        return abs(var_value)
    
    async def _parametric_var(self, returns: pd.Series, confidence_level: float, time_horizon: int) -> float:
        """Calculate VaR using parametric method (normal distribution)"""
        mean = returns.mean()
        std = returns.std()
        z_score = stats.norm.ppf(1 - confidence_level)
        var_value = (mean + z_score * std) * np.sqrt(time_horizon)
        return abs(var_value)
    
    async def _monte_carlo_var(self, returns: pd.Series, confidence_level: float, time_horizon: int, n_simulations: int = 10000) -> float:
        """Calculate VaR using Monte Carlo simulation"""
        mean = returns.mean()
        std = returns.std()
        
        # Generate random scenarios
        random_returns = np.random.normal(mean, std, n_simulations)
        scaled_returns = random_returns * np.sqrt(time_horizon)
        
        percentile = (1 - confidence_level) * 100
        var_value = np.percentile(scaled_returns, percentile)
        return abs(var_value)
    
    async def _cornish_fisher_var(self, returns: pd.Series, confidence_level: float, time_horizon: int) -> float:
        """Calculate VaR using Cornish-Fisher expansion for non-normal distributions"""
        mean = returns.mean()
        std = returns.std()
        skewness = stats.skew(returns)
        kurtosis = stats.kurtosis(returns)
        
        # Standard normal quantile
        z = stats.norm.ppf(1 - confidence_level)
        
        # Cornish-Fisher adjustment
        z_cf = (z + 
                (z**2 - 1) * skewness / 6 + 
                (z**3 - 3*z) * kurtosis / 24 - 
                (2*z**3 - 5*z) * skewness**2 / 36)
        
        var_value = (mean + z_cf * std) * np.sqrt(time_horizon)
        return abs(var_value)
    
    async def _calculate_expected_shortfall(self, returns: pd.Series, confidence_level: float, time_horizon: int) -> float:
        """Calculate Expected Shortfall (Conditional VaR)"""
        percentile = (1 - confidence_level) * 100
        threshold = np.percentile(returns, percentile)
        tail_returns = returns[returns <= threshold]
        
        if len(tail_returns) > 0:
            es_value = tail_returns.mean() * np.sqrt(time_horizon)
            return abs(es_value)
        else:
            return 0.0
    
    async def _apply_stress_scenario(self, portfolio: Dict[str, float], scenario_name: str, scenario: Dict[str, float]) -> StressTestResult:
        """Apply a stress scenario to the portfolio"""
        try:
            # Get current portfolio value (assuming $1M base)
            portfolio_value = 1000000
            
            # Calculate impact for each asset
            individual_impacts = {}
            total_impact = 0
            
            for asset, weight in portfolio.items():
                if asset.upper() in ['CASH', 'USD']:
                    impact = 0
                elif 'equity' in asset.lower() or asset in ['AAPL', 'GOOGL', 'MSFT', 'AMZN', 'TSLA']:
                    impact = scenario.get('equity_shock', 0) * weight * portfolio_value
                elif 'bond' in asset.lower():
                    impact = scenario.get('bond_shock', 0) * weight * portfolio_value
                else:
                    # Default to equity treatment
                    impact = scenario.get('equity_shock', 0) * weight * portfolio_value
                
                individual_impacts[asset] = impact
                total_impact += impact
            
            return StressTestResult(
                scenario_name=scenario_name,
                portfolio_impact=total_impact / portfolio_value,  # As percentage
                individual_impacts=individual_impacts,
                probability_estimate=self._estimate_scenario_probability(scenario_name),
                time_horizon="1 day",
                confidence_level=0.95
            )
            
        except Exception as e:
            self.logger.error(f"Failed to apply stress scenario {scenario_name}: {e}")
            raise
    
    def _estimate_scenario_probability(self, scenario_name: str) -> float:
        """Estimate probability of stress scenario"""
        probabilities = {
            'market_crash_2008': 0.01,  # 1% annual probability
            'covid_crash_2020': 0.005,  # 0.5% annual probability
            'interest_rate_shock': 0.1,  # 10% annual probability
            'inflation_shock': 0.05,  # 5% annual probability
            'geopolitical_crisis': 0.02  # 2% annual probability
        }
        return probabilities.get(scenario_name, 0.01)
    
    async def _get_returns_data(self, assets: List[str], period: int = 252) -> pd.DataFrame:
        """Get historical returns data for assets"""
        try:
            # Check cache first
            cache_key = f"{'-'.join(sorted(assets))}_{period}"
            if cache_key in self.returns_cache:
                cached_data, timestamp = self.returns_cache[cache_key]
                if datetime.now() - timestamp < timedelta(hours=1):  # Cache for 1 hour
                    return cached_data
            
            # Download price data
            end_date = datetime.now()
            start_date = end_date - timedelta(days=period + 30)  # Extra buffer
            
            price_data = yf.download(assets, start=start_date, end=end_date, progress=False)['Adj Close']
            
            if isinstance(price_data, pd.Series):
                price_data = price_data.to_frame()
            
            returns_data = price_data.pct_change().dropna().tail(period)
            
            # Cache the data
            self.returns_cache[cache_key] = (returns_data, datetime.now())
            
            return returns_data
            
        except Exception as e:
            self.logger.error(f"Failed to get returns data: {e}")
            # Return dummy data for demonstration
            dates = pd.date_range(end=datetime.now(), periods=period, freq='D')
            return pd.DataFrame(
                np.random.randn(period, len(assets)) * 0.02,  # 2% daily volatility
                index=dates,
                columns=assets
            )
    
    async def _average_var_estimates(self, var_results: Dict[str, Dict[str, float]], confidence_levels: List[float]) -> Dict[str, float]:
        """Average VaR estimates across different methods"""
        averaged = {}
        
        for confidence_level in confidence_levels:
            var_key = f'var_{int(confidence_level*100)}'
            es_key = f'es_{int(confidence_level*100)}'
            
            var_values = [method_results[var_key] for method_results in var_results.values() if var_key in method_results]
            es_values = [method_results[es_key] for method_results in var_results.values() if es_key in method_results]
            
            if var_values:
                averaged[var_key] = np.mean(var_values)
            if es_values:
                averaged[es_key] = np.mean(es_values)
        
        return averaged
    
    async def _calculate_individual_var(self, returns_data: pd.DataFrame, weights: np.ndarray, confidence_level: float) -> Dict[str, float]:
        """Calculate individual asset VaR contributions"""
        individual_var = {}
        
        for i, asset in enumerate(returns_data.columns):
            asset_returns = returns_data.iloc[:, i]
            percentile = (1 - confidence_level) * 100
            asset_var = abs(np.percentile(asset_returns, percentile))
            individual_var[asset] = asset_var * weights[i]
        
        return individual_var
    
    async def _monitor_risk_limits(self, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Monitor portfolio against risk limits"""
        try:
            portfolio = parameters.get('portfolio', {})
            current_metrics = parameters.get('current_metrics', {})
            
            violations = []
            warnings = []
            
            # Check individual position limits
            for asset, weight in portfolio.items():
                if weight > self.risk_limits['max_individual_weight']:
                    violations.append(RiskAlert(
                        alert_type="POSITION_LIMIT_VIOLATION",
                        severity=AgentPriority.HIGH,
                        message=f"Position in {asset} ({weight:.2%}) exceeds limit ({self.risk_limits['max_individual_weight']:.2%})",
                        affected_assets=[asset],
                        current_value=weight,
                        threshold_value=self.risk_limits['max_individual_weight'],
                        recommendation=f"Reduce {asset} position to {self.risk_limits['max_individual_weight']:.2%}",
                        timestamp=datetime.now()
                    ))
            
            # Check VaR limits
            if 'var_95' in current_metrics:
                if current_metrics['var_95'] > self.risk_limits['portfolio_var_95']:
                    violations.append(RiskAlert(
                        alert_type="VAR_LIMIT_VIOLATION",
                        severity=AgentPriority.CRITICAL,
                        message=f"95% VaR ({current_metrics['var_95']:.2%}) exceeds limit ({self.risk_limits['portfolio_var_95']:.2%})",
                        affected_assets=list(portfolio.keys()),
                        current_value=current_metrics['var_95'],
                        threshold_value=self.risk_limits['portfolio_var_95'],
                        recommendation="Reduce portfolio risk through diversification or position reduction",
                        timestamp=datetime.now()
                    ))
            
            return {
                'violations': [alert.__dict__ for alert in violations],
                'warnings': warnings,
                'limits_status': 'BREACH' if violations else 'COMPLIANT',
                'monitoring_timestamp': datetime.now().isoformat()
            }
            
        except Exception as e:
            self.logger.error(f"Risk monitoring failed: {e}")
            raise
    
    async def _calculate_comprehensive_risk_metrics(self, portfolio_data: Dict[str, Any]) -> RiskMetrics:
        """Calculate comprehensive risk metrics for the portfolio"""
        # This would be implemented with actual portfolio data
        return RiskMetrics(
            var_95=0.025,
            var_99=0.035,
            expected_shortfall_95=0.032,
            expected_shortfall_99=0.045,
            maximum_drawdown=0.08,
            volatility=0.15,
            beta=1.05,
            tracking_error=0.03,
            information_ratio=0.5,
            downside_deviation=0.12,
            calmar_ratio=1.5
        )
    
    async def _generate_risk_alerts(self, portfolio_data: Dict[str, Any], market_data: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Generate risk alerts based on current conditions"""
        return [
            {
                'type': 'CONCENTRATION_RISK',
                'severity': 'MEDIUM',
                'message': 'High concentration in technology sector',
                'recommendation': 'Consider diversification into other sectors'
            }
        ]
    
    async def _quick_stress_test(self, portfolio_data: Dict[str, Any]) -> Dict[str, Any]:
        """Perform quick stress test on portfolio"""
        return {
            'market_crash_scenario': -0.15,
            'interest_rate_shock': -0.08,
            'sector_rotation': -0.05
        }
    
    async def _check_correlation_risks(self, market_data: Dict[str, Any]) -> List[str]:
        """Check for correlation-based risks"""
        return ["High correlation detected between major holdings"]
    
    async def _assess_liquidity_risk(self, portfolio_data: Dict[str, Any]) -> Dict[str, Any]:
        """Assess portfolio liquidity risk"""
        return {
            'liquidity_score': 0.85,
            'days_to_liquidate': 5,
            'liquid_asset_ratio': 0.75
        }
    
    async def _calculate_var_breakdown(self, portfolio_data: Dict[str, Any]) -> Dict[str, Any]:
        """Break down VaR by components"""
        return {
            'individual_contributions': {'AAPL': 0.008, 'GOOGL': 0.007, 'MSFT': 0.006},
            'diversification_benefit': 0.005
        }
    
    async def _analyze_market_regime(self, market_data: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze current market regime"""
        return {
            'current_regime': 'LOW_VOLATILITY',
            'regime_probability': 0.75,
            'expected_duration': 30
        }
    
    # Additional methods would be implemented here for:
    # - _analyze_liquidity
    # - _scenario_analysis  
    # - _decompose_portfolio_risk
    # - _assess_credit_risk
    # - _reverse_stress_test
    # - _monte_carlo_stress_test
    # - _analyze_rolling_correlations
    # - _perform_pca_analysis
    # - _detect_correlation_regimes